name: Release on tag
on:
  create:
    tags:
      - v*

env:
  BUILD_TYPE: Release
  REGISTRY: ghcr.io
  IMAGE_NAME: dmirtydmirty/govnochat


jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/dmirtydmirty/boost1-86-0:latest 
  
    steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ github.workspace }}
  
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
  
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Create artifact
      run: |
          ls
          mkdir -p art
          cp ${{ github.workspace }}/build/ChatServer  art/
          cp Scripts/*  art/
          cp Docker/Dockerfile_release  art/

    - name: Browse_files
      run: ls -a ${{ github.workspace }}
     
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: build-artifact
          path: art/


  
  build-and-push-container:
    needs: build
    runs-on: ubuntu-latest
    
    steps:

    - name:  Download artifact
      uses: actions/download-artifact@v4
      with:
          name: build-artifact
          path: ${{ github.workspace }}

    - name: Log in to the Container registry
      uses:  docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

    - name: build-container
      run: |
           ls ${{ github.workspace }}
           cd ${{ github.workspace }}
           chmod +x ChatServer
           docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} -f Dockerfile_release --build-arg BINARY_PATH=ChatServer  .
           docker tag {{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} {{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Push container
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}


  create-release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
          name: build-artifact
          path: ${{ github.workspace }}

    - name: Fill config
      run: |
            echo "[Settings]
            VERSION=${{ github.ref_name }}
            PORT=15001
            CONTAINER_NAME=GovnoChatServer
            LOG_FILE=govnochat.log" > .ini

    - name: Pack scripts into archive
      run: |
            mkdir release-${{ github.ref_name }}
            cp .ini release-${{ github.ref_name }}

            cp start.*  release-${{ github.ref_name }}
            cp stop.*   release-${{ github.ref_name }}
            cp log.*    release-${{ github.ref_name }}

            zip -r release-${{ github.ref_name }}.zip release-${{ github.ref_name }}



    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body: This is a release build.
        draft: false
        prerelease: false
    
    - name: Upload artifact to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release-${{ github.ref_name }}.zip
        asset_name: release-${{ github.ref_name }}.zip
        asset_content_type: application/zip
