name: Release on tag
on:
  create:
    tags:
      - v*

env:
  BUILD_TYPE: Release
  REGISTRY: ghcr.io
  IMAGE_NAME: dmirtydmirty/govnochat


jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/dmirtydmirty/boost1-86-0:latest 
  
    steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ github.workspace }}
  
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        ls -a
  
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
        ls -a

    - name: Create artifact
      run: |
          ls
          mkdir -p art
          cp ${{ github.workspace }}/build/ChatServer  art/
          cp Docker/Dockerfile_release  art/

    - name: Browse_files
      run: ls -a ${{ github.workspace }}
     
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: build-artifact
          path: art/


  
  build-and-push-container:
    needs: build
    runs-on: ubuntu-latest
    
    steps:

    - name:  Download artifact
      uses: actions/download-artifact@v4
      with:
          name: build-artifact
          path: ${{ github.workspace }}

    - name: Log in to the Container registry
      uses:  docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

    - name: build-container
      run: |
           ls ${{ github.workspace }}
           cd ${{ github.workspace }}
           chmod +x ChatServer
           docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} -f Dockerfile_release --build-arg BINARY_PATH=ChatServer  .

    - name: Push container
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}


 